/**
 * Regression: Safari 3DS callback regression after pay-sdk 4.3
 * Generated by Product OS Code Agent — human must review before merge.
 */
import { describe, it, expect } from "vitest";
import { checkoutHung, sdkVersion } from "@/lib/loop";

describe("Safari 3DS checkout regression", () => {
  it("SDK 4.2.1 rollback does not hang checkout", () => {
    const flags = { pay_sdk_4_3: "off", pay_sdk: "4.2.1" };
    expect(sdkVersion(flags)).toBe("4.2.1");
    expect(checkoutHung(flags)).toBe(false);
  });

  it("flags off after Product OS approve", () => {
    const flags = { pay_sdk_4_3: "off", pay_sdk: "4.2.1" };
    expect(checkoutHung(flags)).toBe(false);
  });
});
